// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwevevndnfvyiwrhoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd2V2ZXZuZG5mdnlpd3Job2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDI1OTMsImV4cCI6MjA3MjQ3ODU5M30.2j7_pZVu5MkNkF7WCZQVzxPSEnECD7cu9QuJzC-y_Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});